### ISSUE TITLE
will leave for 1 hour

### ISSUE THREAD

**Issue by Feterovsky** [githubteacher/githubfordevelopers-april#1]
I have a conflict meeting between 1 and 2 EDT.. Could not jump off. So I'll leave at 1, then will rejoin at 2

**Comment by brianamarie** [comment]
@Feterovsky Thank you for the heads up. 😄 I'm going to close this issue now. Please feel free to open a new one or reopen this one if you have more questions. When you get back, let me know, and I'll do my best to catch you up if you'd like.
