### ISSUE TITLE
Unable to access setting button

### ISSUE THREAD

**Issue by ishusinghal** [githubteacher/githubfordevelopers-april#10]
Unable to access setting button

**Comment by brianamarie** [comment]
@ishusinghal Yep, that's right! Because you aren't an owner of the repository, you won't be able to. When you create your own repositories, you'll see the settings tab. 

I'm going to close this issue for now. Please re-open this or open a new issue if you have more questions. 😄

**Comment by kumardss** [comment]
@ishusinghal owner of the repository only the one who has the access to setting tab.
