### ISSUE TITLE
What is difference between "Fetch" and "Pull" ??

### ISSUE THREAD

**Issue by shidhupatil1149** [githubteacher/githubfordevelopers-april#111]

**Comment by brianamarie** [comment]
@shidhupatil1149 Great question! 'Pull' is a combination command. 

`git pull` = `git fetch` + `git merge`

AKA, `git fetch` updates your remote tracking branches. `git pull` does that, AND updates the branch you're on with any new work on the remote branch. Does that answer your question?

**Comment by shidhupatil1149** [comment]
yes, thank you

**Comment by brianamarie** [comment]
🎉
