### ISSUE TITLE
could not push the second edit

### ISSUE THREAD

**Issue by rujutashinde** [githubteacher/githubfordevelopers-april#115]
Rujutas-MacBook-Pro:githubfordevelopers-april rujutashinde$ git commit -m "Add stubs ti rujutashinde-boston file"
[rujutashinde-boston c91d852] Add stubs ti rujutashinde-boston file
 1 file changed, 7 insertions(+)
Rujutas-MacBook-Pro:githubfordevelopers-april rujutashinde$ git status
On branch rujutashinde-boston
Your branch is ahead of 'origin/rujutashinde-boston' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
Rujutas-MacBook-Pro:githubfordevelopers-april rujutashinde$ git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 348 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: fatal error in commit_refs
To https://github.com/githubteacher/githubfordevelopers-april.git
 ! [remote rejected] rujutashinde-boston -> rujutashinde-boston (failure)
error: failed to push some refs to 'https://github.com/githubteacher/githubfordevelopers-april.git'

**Comment by brianamarie** [comment]
Hm... Let's try a few troubleshooting commands, @rujutashinde.

Can you please copy and paste the output for the following? `git status`, `git branch`, `git remote -v`?

**Comment by rujutashinde** [comment]
was able to do it this time. i think i must have missed out the add step .thanks
