### ISSUE TITLE
Eric isn't mean, and I will refrain from asking if Brianna is from East County

### ISSUE THREAD

**Issue by mtrue01** [githubteacher/githubfordevelopers-april#124]

**Comment by brianamarie** [comment]
@mtrue01 😂 I decline to answer 

cc @hollenberry for lulz

**Comment by mtrue01** [comment]
A branch, a tag, and a reflog walk into a bar. The bartender says, "What is this, some sort of rebase?"

**Comment by brianamarie** [comment]
![](https://media.giphy.com/media/TUtr2Ky56D4Zy/giphy.gif)

**Comment by mtrue01** [comment]
![](https://explainxkcd.com/wiki/images/4/4d/git.png)

**Comment by brianamarie** [comment]
![](https://cdn.meme.am/instances/54884352.jpg)

**Comment by mtrue01** [comment]
![](https://img.memesuper.com/0a3840b473f5f746672d352fe6502bf9_git-meme-git-meme_430-539.jpeg)
