### ISSUE TITLE
Review Videos

### ISSUE THREAD

**Issue by brianamarie** [githubteacher/githubfordevelopers-april#128]
Want to catch up on material before tomorrow? 

https://www.youtube.com/playlist?list=PLg7s6cbtAD16Pgp6WIVfX4VsGI-xyWkMz

**Comment by brianamarie** [comment]
This is day 1 AND day 2, so you won't have to watch all of them to review today's material.

**Comment by kumardss** [comment]
I didn't get you?

**Comment by brianamarie** [comment]
> I didn't get you?

@kumardss I'm not sure what you mean.

**Comment by kumardss** [comment]
This is day 1 AND day 2, so you won't have to watch all of them to review today's material .

Could you please elaborate the above statement?

**Comment by brianamarie** [comment]
> Could you please elaborate the above statement?

Ah, I see, thank you for clarifying @kumardss. Videos 1-7 review the content that we covered today. The remaining videos cover content that we will discuss tomorrow. Does that help?

**Comment by kumardss** [comment]
yes got clarification. Thank you @brianamarie

**Comment by michaelshishkin** [comment]
Briana, when we should expect Day 2 video posted?

**Comment by brianamarie** [comment]
Hi @michaelshishkin. The Day 2 videos are already posted in the same playlist as the other videos.
