### ISSUE TITLE
I can't view the md files from other collaborators in my local git repo

### ISSUE THREAD

**Issue by xdc7** [githubteacher/githubfordevelopers-april#129]
Hi 

I've done a git pull and checked out the master branch, but when I do an `ls -l` I just see one file, the `README.md` and not the `.md` files from the other collaborators.

What am I doing wrong? Please help..

**Comment by brianamarie** [comment]
@xdc7 Just to check - you did a `git pull`, and then `git checkout`?  You didn't do anything wrong - you will need to type `git pull` again before you'll see the updates.

`git pull` is a combination command of `git fetch` and `git merge`. That means it fetches all of the remote tracking branches, but only updates the branch you're currently on. If you did this before you checked out to `master`, that means you only updated the branch you were on, NOT master. Does this make sense?

**Comment by brianamarie** [comment]
I'm going to close now, but please feel free to reopen or open a new issue if you have more questions. 😄
