### ISSUE TITLE
Is a branch the same thing as a fork?

### ISSUE THREAD

**Issue by mtrue01** [githubteacher/githubfordevelopers-april#13]

**Comment by brianamarie** [comment]
@mtrue01 Great question. A branch is NOT the same thing as a fork. We will practice forking tomorrow.

A branch happens within one repository, whereas a fork is creating a new repository with a different owner. Why someone would choose to branch or fork generally depends on the permissions of the original repository. 

I'm going to close this now, but please feel free to reopen or open a new issue if you have more questions. 😄
