### ISSUE TITLE
I already have a personal github page site - will this interfere?

### ISSUE THREAD

**Issue by jongrim** [githubteacher/githubfordevelopers-april#137]
I already have a site hosted at jongrim.github.io - will completing these exercises interfere with that?

**Comment by brianamarie** [comment]
@jongrim Great question! Nope, these will not interfere. Every repository has its own page space.

Your page will still be at `jongrim.github.io`, and this new repo will be at `jongrim.github.io/github-games`. 

Does this answer your question?

**Comment by jongrim** [comment]
Thanks, I suspect as much but wanted to be sure.
