### ISSUE TITLE
Are we still asking questions here?

### ISSUE THREAD

**Issue by limeri** [githubteacher/githubfordevelopers-april#138]

**Comment by brianamarie** [comment]
@limeri Yep! Do you have a question?

**Comment by limeri** [comment]
Why do you push the local branch to remote repo instead of merging locally and pushing that update up?

**Comment by brianamarie** [comment]
@limeri Great question! Technically, there's no difference with how the commits would appear on master. But, we're practicing method that we'd apply in a team setting. If we merge before pushing, we miss out on the pull request step.

The pull request step is really where the magic happens - test can be run automatically, code review happens, and there's a solid context around changes in the future.

Does this answer your question?

**Comment by limeri** [comment]
So we do it this way so we can do a review?  If we're not at the review step, then it doesn't matter?

**Comment by limeri** [comment]
But then you'd need to communicate to team members that they need to pull.

**Comment by brianamarie** [comment]
@limeri You're right. For today it doesn't "matter", but we're practicing the steps in the recommended best practice for collaborative workflows. We'll practice merging locally later.

**Comment by limeri** [comment]
k, thanks.  Will we also practice reviews later?

**Comment by brianamarie** [comment]
@limeri Unfortunately we won't have time to practice reviews again. ☹️ [This video is a good review of our class activity and code reviews](https://www.youtube.com/watch?v=XKSrjdvfzyE&index=5&list=PLg7s6cbtAD16Pgp6WIVfX4VsGI-xyWkMz).

**Comment by brianamarie** [comment]
I'm going to close for now, but please feel free to reopen or to open a new issue if you have more questions.
