### ISSUE TITLE
What happen with the local readme-update branch?

### ISSUE THREAD

**Issue by gallelloit** [githubteacher/githubfordevelopers-april#139]
How is it deleted now it was deleted in the server?

**Comment by gallelloit** [comment]
(I thought that a git pull would do it, but it didn't)

**Comment by brianamarie** [comment]
@pgbonino Great question!

It was deleted on the remote, but not locally. This doesn't happen automatically with pull. You can use `git pull --prune` or `git fetch --prune` to delete the **remote tracking branches**, and `git branch -d <branchname>` to delete the local working branch. (You'll have to be checked out to a different branch, it won't let you delete a branch while you're on it.)

Does this answer your question?

**Comment by gallelloit** [comment]
Yeah!! He just said it too :) I didn't notice I had to do it manually

Thank you
