### ISSUE TITLE
Yesterday's prune error?

### ISSUE THREAD

**Issue by narrly** [githubteacher/githubfordevelopers-april#140]
Did you ever figure out yesterdays prune error?

**Comment by brianamarie** [comment]
Hmm @narrly I don't remember exactly what you're talking about - I'm going to mention @hollenberry so that during the break or after class, he'll be able to answer. 😄

**Comment by narrly** [comment]
This was at the very end of class after deleting our branch and then when prune was applied an error was occurring.

**Comment by brianamarie** [comment]
Oh, that's right, thanks for the detail @narrly. @hollenberry reached out to a colleague for an answer. Here are his notes: (posted with permission)

> <img width="1060" alt="screen shot 2017-04-03 at 3 10 35 pm" src="https://cloud.githubusercontent.com/assets/13326548/24634033/98229b32-1880-11e7-8f10-8e663f3c4c1d.png">

> This error was super strange! I didn't ever check out to the branch in question, so it was strange to me that the  merge was triggering. StackOverflow pointed me [here](http://stackoverflow.com/questions/11796580/git-pull-error-error-remote-ref-is-at-but-expected) : `git update-ref -d refs/remotes/origin/user`

> This worked! I'm not 💯 on why, but thought I'd leave the notes for the next surprised trainer who might run into something similar in the future. Writing this out also helps me to remember for the future.

**Comment by brianamarie** [comment]
Does this answer your question @narrly?

**Comment by hollenberry** [comment]
@narrly Essentially, you'll have to type `git update-ref -d refs/remotes/origin/kumardss` and then you can pull --prune without issue.

**Comment by narrly** [comment]
Ok. I get it now. Yes, this answers my question.
