### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by kumardss** [githubteacher/githubfordevelopers-april#141]
git lol
fatal: unrecognized argument: --online

**Comment by brianamarie** [comment]
@kumardss I think you might have a spelling error. Try `git log --oneline`, not `git log --online`. 

Does this answer your question?

**Comment by kumardss** [comment]
$ git lol
git: 'lol' is not a git command. See 'git --help'.

Did you mean this?
        log

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lof
git: 'lof' is not a git command. See 'git --help'.

Did you mean this?
        log

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git config --global alias.lol "log --online --graph --decorate --all"

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git config --global alias.lol "log --online --graph --decorate --all"

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

**Comment by kumardss** [comment]
$ git log --oneline
328b804 Merge pull request #1 from kumardss/readme-update
d0d3d68 Update README url
5416d65 change shape colors
2710412 change index.html to inde.html
7b5464c change stats display color to green
b7454c1 initializing git repo with all files

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git log --oneline --graph
*   328b804 Merge pull request #1 from kumardss/readme-update
|\
| * d0d3d68 Update README url
|/
* 5416d65 change shape colors
* 2710412 change index.html to inde.html
* 7b5464c change stats display color to green
* b7454c1 initializing git repo with all files

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git log --oneline --graph --decorate
*   328b804 (HEAD -> gh-pages, origin/gh-pages, origin/HEAD) Merge pull request                                                                                                                 #1 from kumardss/readme-update
|\
| * d0d3d68 (origin/readme-update) Update README url
|/
* 5416d65 change shape colors
* 2710412 (origin/shape-colors) change index.html to inde.html
* 7b5464c change stats display color to green
* b7454c1 initializing git repo with all files

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git log --oneline --graph --decorate --all
*   328b804 (HEAD -> gh-pages, origin/gh-pages, origin/HEAD) Merge pull request                                                                                                                 #1 from kumardss/readme-update
|\
| * d0d3d68 (origin/readme-update) Update README url
|/
| * 58aea7b (origin/game-instructions) add warning
| * 02f01db add game goal
| * 4732179 add how to rotate shape
| * aa5d175 add instruction section and how to start the game
|/
* 5416d65 change shape colors
* 2710412 (origin/shape-colors) change index.html to inde.html
* 7b5464c change stats display color to green
| * c5b2523 (origin/stats-update) change stats display color to yellow
|/
* b7454c1 initializing git repo with all files

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
git: 'lol' is not a git command. See 'git --help'.

Did you mean this?
        log

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lof
git: 'lof' is not a git command. See 'git --help'.

Did you mean this?
        log

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git config --global alias.lol "log --online --graph --decorate --all"

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git config --global alias.lol "log --online --graph --decorate --all"

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lof
git: 'lof' is not a git command. See 'git --help'.

Did you mean one of these?
        log
        lol

Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages                                                                                                                )
$ git lol
fatal: unrecognized argument: --online

**Comment by brianamarie** [comment]
@kumardss Ah, I see. So when you typed 

> Sudheer@Sudheer MINGW64 /e/Education (H)/GitHub/classrepo/github-games (gh-pages )
> $ git config --global alias.lol "log --online --graph --decorate --all"

There was a spelling error. Try typing `git config --global alias.lol "log --oneline --graph --decorate --all"`. Then, `git lol` should work.

**Comment by kumardss** [comment]
Thank you

**Comment by brianamarie** [comment]
👍 🎉

**Comment by kumardss** [comment]
$ git s
git: 's' is not a git command. See 'git --help'.

Did you mean one of these?
        show
        status
        svn

**Comment by brianamarie** [comment]
@kumardss Yep - Eric set up a challenge. To have it do status with s, you'd need to set a git alias. 😄

**Comment by kumardss** [comment]
?

**Comment by kumardss** [comment]
git config --global alias.s "status --oneline --graph --decorate --all" 

is above command correct?

**Comment by brianamarie** [comment]
@kumardss Just like `git lol` is an alias for `git log --oneline --graph --decorate --all`, Eric has set `git s` to be the same as `git status`. This is not a required function for the class, he was just demonstrating.

**Comment by brianamarie** [comment]
> git config --global alias.s "status --oneline --graph --decorate --all"

@kumardss That would set `git s` to be `git status --oneline --graph --decorate --all`, which isn't what you want. You want it to be `git status`. So, you'd type git config --global alias.s "status"

**Comment by kumardss** [comment]
thank you

**Comment by brianamarie** [comment]
👍
