### ISSUE TITLE
Can you please upload the commands doument

### ISSUE THREAD

**Issue by rrperkit** [githubteacher/githubfordevelopers-april#142]
It will be helpful if you create and upload as document all the commands that you copying in the right window.

**Comment by brianamarie** [comment]
@rrperkit I will pass this along to @hollenberry. He may not be able to get to it until the break, but I will see.

**Comment by rrperkit** [comment]
Sure Thank you.

**Comment by karamheen** [comment]
Most of the commands are mentioned in the following document:
https://github.github.io/training-manual/

**Comment by rrperkit** [comment]
Yes Manual has that info..but it is all scattered, 

It will be nice to have all these commands handy, so that we can refer to it easily.
You can just copy and paste all the commands here as a comment.

**Comment by rrperkit** [comment]
@brianamarie ? Can you please copy and paste the commands as comments to this thread

**Comment by brianamarie** [comment]
@rrperkit I don't have them, they're on Eric's computer, but after he's done teaching class he will post them. He will probably post them in a new issue.

**Comment by rrperkit** [comment]
@eric-m-christian , can you please upload document.

**Comment by hollenberry** [comment]
https://github.com/githubteacher/githubfordevelopers-april/blob/master/clihistory

Here you go! Please let me know if there's anything else you need.
