### ISSUE TITLE
Question on the visualization

### ISSUE THREAD

**Issue by welchn** [githubteacher/githubfordevelopers-april#143]
Are the gray circles local, and the green circles on github?

**Comment by brianamarie** [comment]
@welchn This visual representation isn't consider local and remote - so as long as you're thinking that it's just one or the other (local or remote), you'll be thinking of it accurately. Does that make sense?

**Comment by welchn** [comment]
I think so...we are looking at the state of the branches, regardless of the source of the commits?

**Comment by brianamarie** [comment]
@welchn Exactly! 👍

**Comment by welchn** [comment]
Thanks!
