### ISSUE TITLE
How can we set atom as the default text editor?

### ISSUE THREAD

**Issue by Xukinorris** [githubteacher/githubfordevelopers-april#147]

**Comment by karamheen** [comment]
git config --global core.editor "atom --wait"

Above works for OS X.

**Comment by brianamarie** [comment]
@Xukinorris [Here's some more documentation](https://help.github.com/articles/associating-text-editors-with-git/), to add onto what @karamheen said. 😄

**Comment by brianamarie** [comment]
@Xukinorris I'm going to close this issue, but please feel free to reopen or to open a new issue if you have more questions. 👍
