### ISSUE TITLE
I didn't see the same error Eric got when I tried to merge gh-pages and stats-update

### ISSUE THREAD

**Issue by limeri** [githubteacher/githubfordevelopers-april#148]

**Comment by limeri** [comment]
It looks like I checked out incorrectly:

$ git branch --all
* gh-pages
  readme-update
  stats-update
  remotes/origin/HEAD -> origin/gh-pages
  remotes/origin/game-instructions
  remotes/origin/gh-pages
  remotes/origin/shape-colors
  remotes/origin/stats-update

**Comment by brianamarie** [comment]
@limeri I'm not sure I understand - what are you expecting to see differently?

**Comment by limeri** [comment]
I think I got it.

**Comment by limeri** [comment]
I had both local and remote branches called "stats-update".  I checked stats-update out wrong because I created a local version.

**Comment by brianamarie** [comment]
Ah, I see. Do you have more questions, or did you figure it all out?

**Comment by brianamarie** [comment]
I'm going to close now, but please feel free to reopen or open a new issue if you have more questions. 👍
