### ISSUE TITLE
git pull --prune doesn't seem to remove the branch that has been removed

### ISSUE THREAD

**Issue by kraghuram** [githubteacher/githubfordevelopers-april#149]
when I run 'git branch --all'  I still see the branch that has been removed with 'git branch -d <branch-name>'.

**Comment by brianamarie** [comment]
@kraghuram Hm. Let's see what branch you're on now: If you type `git status` what is the output? If you're on `gh-pages`, you might want to try deleting it again.

What might have happened is that you tried to delete the branch while you were still on it - in that case, it wouldn't let you delete it.

**Comment by kraghuram** [comment]
I believe I have deleted when I am on the master(gh-pages): The following is what I see now:


$ git branch --all
* gh-pages
  stats-update
  remotes/origin/HEAD -> origin/gh-pages
  remotes/origin/game-instructions
  remotes/origin/gh-pages
  remotes/origin/readme-update
  remotes/origin/shape-colors
  remotes/origin/stats-update
$ git branch -d remotes/origin/readme-update
error: branch 'remotes/origin/readme-update' not found.
$

**Comment by brianamarie** [comment]
@kraghuram Ah, I see. You deleted the local working branch, but not the remote tracking branch. To do that, type `git fetch --prune`.

**Comment by kraghuram** [comment]
I believe I have done that already, but trying again:


$ git fetch --prune
$ git branch --all
* gh-pages
  stats-update
  remotes/origin/HEAD -> origin/gh-pages
  remotes/origin/game-instructions
  remotes/origin/gh-pages
  remotes/origin/readme-update
  remotes/origin/shape-colors
  remotes/origin/stats-update
$

**Comment by brianamarie** [comment]
@kraghuram Did you delete the branch on the remote?

**Comment by kraghuram** [comment]
ah, I didn't do that.  How do I do that?

**Comment by brianamarie** [comment]
@kraghuram You can delete it from the pull request, or from [this page](https://github.com/kraghuram/github-games/branches).

**Comment by kraghuram** [comment]
thx Brian.

**Comment by brianamarie** [comment]
👍
