### ISSUE TITLE
Why did Eric only use the first 5 digits of the commit ID?  Could we have copied and pasted the whole thing?

### ISSUE THREAD

**Issue by limeri** [githubteacher/githubfordevelopers-april#151]

**Comment by brianamarie** [comment]
@limeri You could copy and paste the whole thing. But, with most repositories, only the first 4 characters are necessary. With large repositories, sometimes the minimum grows to 5 or 6.  Does this answer your question?

**Comment by limeri** [comment]
Yes, thanks

**Comment by brianamarie** [comment]
👍
