### ISSUE TITLE
I feel that this session is very complicated for me

### ISSUE THREAD

**Issue by kumardss** [githubteacher/githubfordevelopers-april#152]

**Comment by kumardss** [comment]
i am unable to grab the concept

**Comment by brianamarie** [comment]
@kumardss Yes, this last hour and the next hour are more advanced. If you don't understand everything that's OK. The main purpose of this advanced content is to prepare you for what to watch out for in the future and let you know how git deals with certain problems on a large scale. 

Also, the review videos cover this information and it is in the [training manual](https://github.github.io/training-manual)

**Comment by karamheen** [comment]
@kumardss It will be helpful if you can mention which exact concept you are talking about.

**Comment by brianamarie** [comment]
@kumardss I'm going to close this issue for now, but please feel free to reopen or to open a new issue if you have some more questions. 👍
