### ISSUE TITLE
lost sync

### ISSUE THREAD

**Issue by cppIr0nman** [githubteacher/githubfordevelopers-april#153]
FYI: Could not follow up with all git commands because atom was not my default editor in windows 10 (lost sync just before bisecting).
I am just watching now.
Being new to all this my question is this: is there any way to redo what I missed on my fork after the class ends?
Thanks.

**Comment by brianamarie** [comment]
@cppIr0nman Yes, the [review videos here](https://github.com/githubteacher/githubfordevelopers-april/issues/128) will help you review. Does this answer your question?

**Comment by cppIr0nman** [comment]
Ok, will try to use the videos. IMO some things should have been set at the beginning of the course yesterday - like general settings, e.g. default editor - so everybody is on the same page.
Thanks.

**Comment by cppIr0nman** [comment]
Also, the class should be for different levels; being a begginer and having other with 6 months+ git experience does not feel right.

**Comment by brianamarie** [comment]
> Ok, will try to use the videos. IMO some things should have been set at the beginning of the course yesterday - like general settings, e.g. default editor - so everybody is on the same page.
> Thanks.

@cppIr0nman Thank you for this feedback - we tend to avoid default editor because so many developers already have a specific editor that they prefer set up. Are there any other configs or settings that you think would help to have set up at the beginning of class? 

> Also, the class should be for different levels; being a begginer and having other with 6 months+ git experience does not feel right.

@cppIr0nman I'm sorry you feel the pacing isn't quite right, but I do appreciate the feedback. We are always trying to iterate on our offerings to provide the best experience possible and this type of feedback is important!

**Comment by cppIr0nman** [comment]
Only videos will be available? A text file with the git command history would be helpful as well.

**Comment by brianamarie** [comment]
@cppIr0nman There are many resources listed in the [README.md](https://github.com/githubteacher/githubfordevelopers-april/blob/master/README.md) of this repository in addition to the videos. Eric also said he would post his command history in an issue once class was over.

**Comment by cppIr0nman** [comment]
Thanks.

**Comment by brianamarie** [comment]
@cppIr0nman I'm going to close this issue for now, but please feel free to reopen or to open a new issue if you have more questions. 👍
