### ISSUE TITLE
pros/cons bash vs cmd for git in windows?

### ISSUE THREAD

**Issue by lmillea** [githubteacher/githubfordevelopers-april#154]

**Comment by brianamarie** [comment]
@lmillea We recommend using `git bash` because the commands will be more consistent across tutorials and online resources.

**Comment by lmillea** [comment]
@brianamarie Thanks.

**Comment by karamheen** [comment]
In addition to what @brianamarie said, from experience I can say that if you setup the PATH correctly for cmd prompt on windows, there is not much difference.

**Comment by lmillea** [comment]
@karamheen Thanks. That's been my experience thus far, too. I was wondering if there was maybe some difference in features or functionality.

**Comment by brianamarie** [comment]
> I was wondering if there was maybe some difference in features or functionality.

@lmillea I think you've got it down - it really comes down to preference.

**Comment by brianamarie** [comment]
@lmillea I'm going to close this now, but feel free to reopen or to open a new issue if you have more questions. 👍
