### ISSUE TITLE
Does he still need to do a "git merge"?

### ISSUE THREAD

**Issue by limeri** [githubteacher/githubfordevelopers-april#156]

**Comment by brianamarie** [comment]
@limeri You're right - he didn't merge yet. Because of time, we're stopping before it's complete and moving on. He went over the hard part, so that you can practice after class if you'd like.

**Comment by limeri** [comment]
k, thanks.  That felt incomplete however, cuz I was confused about completing the merge from a remote branch.

**Comment by brianamarie** [comment]
@limeri Ah, I see. You have a good point. There were a few things going on in that one. Do you feel OK about it, or do you have some questions?

**Comment by limeri** [comment]
I'm good, thanks.
