### ISSUE TITLE
[Off-topic] MacOS Terminal

### ISSUE THREAD

**Issue by Xukinorris** [githubteacher/githubfordevelopers-april#16]
@githubteacher How did you set your terminal to look like this?

**Comment by brianamarie** [comment]
I think this may be what you're looking for: https://gist.github.com/githubteacher/e75edf29d76571f8cc6c


I'm going to close this issue for now, but please feel free to reopen or open a new issue if you have more questions 😄

**Comment by Xukinorris** [comment]
Thanks for the info, can you share his .bash_profile too?

**Comment by Xukinorris** [comment]
@brianamarie

**Comment by brianamarie** [comment]
@hollenberry More requests for your bash info 😄

**Comment by Xukinorris** [comment]
Thanks @brianamarie !

@hollenberry Would you mind? 😁

**Comment by githubteacher** [comment]
Hey @Xukinorris  !

I use https://github.com/sorin-ionescu/prezto! 

You'll have to set up the git configuration after installing the default (it's built in, but you have to navigate to unlock it), but get started there and let me know if you have any extra questions/follow-ups 👍 😄
