### ISSUE TITLE
Atom - installation and use

### ISSUE THREAD

**Issue by githubstudent2016** [githubteacher/githubfordevelopers-april#18]
Hi Brianna, will there a discussion/demo on using Atom later? I was a minute late coming back from break. Not sure if I missed it.

**Comment by brianamarie** [comment]
@githubstudent2016 Good question - we will not be covering the details of Atom. But, if you'd like to set it up, I can point you to some resources so you can work on it during the breaks. 

https://atom.io/
https://help.github.com/articles/associating-text-editors-with-git/

I'm going to close this issue now, but let me know if you have more questions by reopening or opening a new issue. 😄
