### ISSUE TITLE
Question about web UI

### ISSUE THREAD

**Issue by welchn** [githubteacher/githubfordevelopers-april#20]
Hi Briana, this web UI that we are using...is it analogous to the GUI that I downloaded as part of the git Windows 2.12.2 package?  I have not yet run that GUI, but am wondering if it is the same thing as this web GUI.  Also, is the web GUI functionally the same as git cli?

**Comment by brianamarie** [comment]
@welchn Great question. No, the web UI is different than the GUI. We won't be using the GUI today, because the functionality is not quite as robust as Git CLI.  Does this answer your question?

**Comment by welchn** [comment]
Yes, thank you!
