### ISSUE TITLE
Branches and Forks I get, now what about "clones"?

### ISSUE THREAD

**Issue by mtrue01** [githubteacher/githubfordevelopers-april#21]
So thinking in terms of SVN

Branch - Changing code within the same repository
Fork - Copying the code base to a "linked" repository and making changes on that
Clone - An unlinked copy of a repository and I guess a new project
Are these right? 

Are we going to get into things like pull, fetch. merge and rebase?

**Comment by brianamarie** [comment]
@mtrue01 You are close! 

Clone - a local copy of a repository, linked with the remote repository that it is cloned from. We will talk more about this, as well as branching and forking.

We will get into pull, fetch, and merge today and rebase tomorrow. 

I'm going to close this for now, but please feel free to reopen or open a new issue if you have more questions. 😄
