### ISSUE TITLE
I'm having an ssl problem when I try to clone this repo.  Where do I get the cert?

### ISSUE THREAD

**Issue by limeri** [githubteacher/githubfordevelopers-april#22]

**Comment by brianamarie** [comment]
@limeri Make sure you are cloning with HTTPS, not SSL. https://help.github.com/articles/cloning-a-repository/

**Comment by brianamarie** [comment]
Let me know if this doesn't work.

**Comment by limeri** [comment]
I'm using:
git clone https://github.com/githubteacher/githubfordevelopers-april.git

**Comment by brianamarie** [comment]
@limeri Ok. Can you please copy and paste the output that you get when you try to clone?

**Comment by limeri** [comment]
fatal: unable to access 'https://github.com/githubteacher/githubfordevelopers-april.git/': SSL certificate problem: unable to get local issuer certificate

**Comment by brianamarie** [comment]
@limeri Hm...a few things could be causing this. Do you usually clone with SSL? Or, are you inside a company firewall?

**Comment by limeri** [comment]
I'm in a company firewall.  I usually use https.

**Comment by limeri** [comment]
Inside Dell

**Comment by brianamarie** [comment]
Ok @limeri. Unfortunately, as you can imagine, I can only help so much as someone outside of your company firewall. 

Is there someone around you who is doing the training and who is able to clone? Or are you able to connect with a proxy?

**Comment by limeri** [comment]
Got it.  We had a local cert and I removed it from the .gitconfig.

**Comment by brianamarie** [comment]
Perfect, I'm glad to hear it! I'm going to close this issue for now, but please reopen or open a new issue if you have more questions. 😄
