### ISSUE TITLE
All Good, but WHY?

### ISSUE THREAD

**Issue by tsscam** [githubteacher/githubfordevelopers-april#23]
Hello---- Why when I do LS do I get ALL this garbage? --- waiting till end of this or later today for a response is fine, but THANK YOU!

tssca (master *+) Desktop $ ls

'ATT CHANELS.xlsx'
 ch02-1/
 classrepo/
 desktop.ini
 Dropbox.lnk*
'GIT Files SAVED - Shortcut.lnk'*
'Git Hub Mark Down.txt'
'Git Shell.lnk'*
 Github/
 GitHub.appref-ms
 gittest/
 labs/
 Output-Build.txt
'PowerPoint 2016.lnk'*
'Receipt.TXT doc.txt'
'Recording #15.mp4'
 Slack.lnk*
'Week # 1 DQ Questions.docx'

**Comment by brianamarie** [comment]
Hi @tsscam! This means that all of those files - or "garbage" as you call it 😂 - these are the files that are currently on your Desktop. My guess is that these are the icons that you see on your computer desktop, just shown in a different form. Does that answer your question?

**Comment by brianamarie** [comment]
@tsscam It also appears that you may have typed `git init` inside of your C drive. Type `rm -rf .git` to solve this.

**Comment by tsscam** [comment]
PERFECT! Thank you!

**Comment by brianamarie** [comment]
👍 😄 🎉

**Comment by tsscam** [comment]
I closed out & came back & it looked good. I did it again & it's back to like it was. Also, none of my commands are working - GIT STATUS, GIT LOG
tssca ~ $ git status
fatal: Not a git repository (or any of the parent directories): .git
tssca ~ $ git log
fatal: Not a git repository (or any of the parent directories): .git
tssca ~ $

**Comment by brianamarie** [comment]
Okay, @tsscam. You'll need to `cd` into the directory where you cloned the repository. Does that make sense?

**Comment by tsscam** [comment]
yes, but same response
tssca ~ $ cd desktop
tssca desktop $ git status
fatal: Not a git repository (or any of the parent directories): .git
tssca desktop $

**Comment by brianamarie** [comment]
@tsscam I think you have one more to go - try `cd classrepo`, then `git status`.

**Comment by tsscam** [comment]
fatal: Not a git repository (or any of the parent directories): .git

**Comment by brianamarie** [comment]
@tsscam The problem here is we aren't in the class repository, and I don't know where you cloned it. 😄 Did you maybe clone it into the `GitHub` directory? If you aren't sure, you could always open up explorer or finder and look for the repository that way. Once we know the 'path' of the class repository, we'll be in good shape!

**Comment by brianamarie** [comment]
Closing out because of the more recent issue
