### ISSUE TITLE
Clone is just timing out

### ISSUE THREAD

**Issue by doakd** [githubteacher/githubfordevelopers-april#24]
I am inside my company's network.  That might be the cause:

Cloning into 'githubfordevelopers-april'...
fatal: unable to access 'https://github.com/githubteacher/githubfordevelopers-ap
ril.git/': Failed to connect to github.com port 443: Timed out

**Comment by brianamarie** [comment]
@doakd Hm, I see. Since you're inside of a network, is there a proxy that you could use?

**Comment by brianamarie** [comment]
It's been about an hour, so I'm going to close this issue. Please reopen or open a new issue if you have more questions. 😄
