### ISSUE TITLE
issue with WINDOWS command

### ISSUE THREAD

**Issue by githubstudent2016** [githubteacher/githubfordevelopers-april#25]
Hi Brianna,

Here is the error I am getting with teh command - WINDOWS. I am on a WINDOWS system.

$ WINDOWS - git config --global core.autocrlf true
bash: WINDOWS: command not found

**Comment by brianamarie** [comment]
@githubstudent2016 It looks like you may be typing this:

`WINDOWS - git config --global core.autocrlf true`

If so, try typing this:

`git config --global core.autocrlf true`

If that doesn't work, try typing `git --version` and let me know what it says. 😄

**Comment by brianamarie** [comment]
It's been about an hour, so I'm going to close this issue. Please reopen or open a new issue if you have more questions. 😄
