### ISSUE TITLE
$ git config --global --list ?

### ISSUE THREAD

**Issue by kumardss** [githubteacher/githubfordevelopers-april#26]
- user.name=kumardss user.email=kumardss@outlook.com filter.lfs.process=git-lfs filter-process filter.lfs.required=true filter.lfs.clean=git-lfs clean -- %f filter.lfs.smudge=git-lfs smudge -- %f push.default=simple

**Comment by brianamarie** [comment]
@kumardss What's your question? 😄

**Comment by kumardss** [comment]
i think some options are not getting for me compared to @githubteacher

**Comment by kumardss** [comment]
after executing the git config --global --list command

**Comment by brianamarie** [comment]
AH, I see. You're right! That's OK. Eric has a lot of settings, but they're not all required. You have all of the required settings. 👍 I'm going to close this issue now, but if you have more questions, please feel free to reopen or to open a new issue.
