### ISSUE TITLE
My branch is visible on github but I cannot checkout branch in gitbash. why?

### ISSUE THREAD

**Issue by vedashreevinay** [githubteacher/githubfordevelopers-april#28]

**Comment by brianamarie** [comment]
@vedashreevinay If you type `git status`, what is the output?

**Comment by vedashreevinay** [comment]
pathspec 'vedashreevinay-clarksburg' did not match any file(s) known to git. is the error I see

**Comment by brianamarie** [comment]
> pathspec 'vedashreevinay-clarksburg' did not match any file(s) known to git. is the error I see

@vedashreevinay Is that what you see when you type `git status`?

**Comment by vedashreevinay** [comment]
no.

$ git checkout vedashreevinay-clarksburg
error: pathspec 'vedashreevinay-clarksburg' did not match any file(s) known to git.

**Comment by brianamarie** [comment]
Okay. What is the output if you type `git status`? Please type that and post the output here, as well as the output for the command `git branch --all`.

**Comment by vedashreevinay** [comment]
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

$ git branch --all
* master
  remotes/origin/@ishusinghal
  remotes/origin/DavidGPeterson-Milford
  remotes/origin/Feterovskiy_Raleigh
  remotes/origin/GPrathyusha-Ashburn
  remotes/origin/Githubstudent2016_Shrewsbury
  remotes/origin/HEAD -> origin/master
  remotes/origin/MaxG117-LA
  remotes/origin/Pgbonino-badajoz
  remotes/origin/RexHamilton-StCatharines
  remotes/origin/SarithaPalley_Norfolk
  remotes/origin/Shalini-Hopkinton
  remotes/origin/TSSCAMARO_Detroit
  remotes/origin/amitak_losangeles
  remotes/origin/aoharris-hopkinton
  remotes/origin/ckimaru-Nashua
  remotes/origin/connoj16-marlborough
  remotes/origin/cppIr0nman-Deerfield
  remotes/origin/cr-tadd-hayward
  remotes/origin/czubocha-wroclaw
  remotes/origin/dca1320-boston
  remotes/origin/doakd-battleground
  remotes/origin/dshenan-ATL
  remotes/origin/elena---Westborough
  remotes/origin/emcjoe-cromwell
  remotes/origin/emilym-sba-exeter
  remotes/origin/emyers123-denver
  remotes/origin/eric-m-christian-nashua
  remotes/origin/francm2-foxboro
  remotes/origin/githubteacher-sandiego
  remotes/origin/ichandra12-sandiego
  remotes/origin/ishusinghal-pune
  remotes/origin/jml9904-hopkinton
  remotes/origin/jongrim-atlanta
  remotes/origin/jrbird50-milford
  remotes/origin/kalags-mysore
  remotes/origin/karajl-morrisville
  remotes/origin/karam-menlopark
  remotes/origin/khaland-WB
  remotes/origin/kkondapa-Norfolk-VA
  remotes/origin/kraghuram-fremont
  remotes/origin/kumardss-Hyderabad
  remotes/origin/labajt-northborough
  remotes/origin/leef6-mountainview
  remotes/origin/leefp-webo
  remotes/origin/limeri-framingham
  remotes/origin/lmillea-wheaton
  remotes/origin/luizguilhermegl-brasilia
  remotes/origin/master
  remotes/origin/mbendure-Cincinnati
  remotes/origin/michaelshishkin-edenprairie
  remotes/origin/mrgcode-hopkinton
  remotes/origin/mtrue01-AndoverMA
  remotes/origin/narrly-edenprairie
  remotes/origin/natalia-souza_Brasilia
  remotes/origin/phanss-mumbai
  remotes/origin/poojadesai22-mumbai
  remotes/origin/rchillar-fortworth
  remotes/origin/rgredvig-minnetonka
  remotes/origin/rujutashinde-boston
  remotes/origin/sanjaysy456-bangalore
  remotes/origin/sanjiv1980-patna
  remotes/origin/shan-mpk
  remotes/origin/shidhupatil1149
  remotes/origin/smanjrekar-sandiego
  remotes/origin/smchone-Cincinnati
  remotes/origin/sxk6935-Mumbai
  remotes/origin/syeremenko-chicago
  remotes/origin/theorybeta-toronto
  remotes/origin/thotchen-leeds
  remotes/origin/vishn412-durham
  remotes/origin/visw2290-chennai
  remotes/origin/wca2000-hopkinton
  remotes/origin/welchn-charlton
  remotes/origin/xdc7-chicago
  remotes/origin/xukinorris-brasilia
  remotes/origin/xurinorris-brasilia
  remotes/origin/ydong8800-boston
  remotes/origin/yinglimao-raleigh
  remotes/origin/yogeshpgarud-pune
  remotes/origin/zettabytecode-losangeles

**Comment by vedashreevinay** [comment]
![image](https://cloud.githubusercontent.com/assets/5796687/24623069/3b702d4c-1875-11e7-9512-d3f17e6fbb89.png)

**Comment by brianamarie** [comment]
Okay. Try `git pull`, then `git branch --all` again. Did you create the branch after you cloned?

**Comment by vedashreevinay** [comment]
yes, 
I think I created branch after I cloned

**Comment by vedashreevinay** [comment]
I did a git pull and then it worked. Thanks!

**Comment by brianamarie** [comment]
Great! 🎉
