### ISSUE TITLE
Recommended bash profile for iTerm2 (MAC)?

### ISSUE THREAD

**Issue by rchillard-gov** [githubteacher/githubfordevelopers-april#30]
Do you have a recommended bash profile for iTerm2 (MAC)?

**Comment by brianamarie** [comment]
Whatever works for you, @rchillar. We don't recommend anything specific. If you're wondering, I think this may be what you're looking for: https://gist.github.com/githubteacher/e75edf29d76571f8cc6c

I'm going to close this issue for now, but please feel free to reopen or open a new issue if you have more questions 😄

**Comment by rchillard-gov** [comment]
@brianamarie what is the profile being used by the presenter?  I like the color coding and the branch display.

**Comment by brianamarie** [comment]
@hollenberry After class, do you mind sharing your info here?

**Comment by rchillard-gov** [comment]
Thank you Briana!

**Comment by githubteacher** [comment]
Hey @rchillar !

I use https://github.com/sorin-ionescu/prezto! 

You'll have to set up the git configuration after installing the default (it's built in, but you have to navigate to unlock it), but get started there and let me know if you have any extra questions/follow-ups 👍 😄
