### ISSUE TITLE
how to get the branch name on the command line ( terminal ) 

### ISSUE THREAD

**Issue by yogeshpgarud** [githubteacher/githubfordevelopers-april#31]

**Comment by brianamarie** [comment]
I think this may be what you're looking for: https://gist.github.com/githubteacher/e75edf29d76571f8cc6c

I'm going to close this issue for now, but please feel free to reopen or open a new issue if you have more questions 😄

**Comment by yogeshpgarud** [comment]
thanks , its working fine now
