### ISSUE TITLE
Whats an example of an edge case when you

### ISSUE THREAD

**Issue by mtrue01** [githubteacher/githubfordevelopers-april#32]

**Comment by brianamarie** [comment]
@mtrue01 What is your question? 😄

**Comment by mtrue01** [comment]
When do you need to use   remotes/origin/mtrue01-AndoverMA  instead of just the branch name?

Also I see this at work a lot on things we do, is this meaning that remotes is "remote", origin is my original checkout source and the branch is my branchname...right?

**Comment by brianamarie** [comment]
@mtrue01  You're right on. 



> When do you need to use remotes/origin/mtrue01-AndoverMA instead of just the branch name?

If we had multiple remotes connected with this repository clone, we would specify `git checkout origin/mtrue01-AndoverMA`, but with only one remote this isn't necessary. Does this answer your question?

**Comment by mtrue01** [comment]
Yep. thanks :)
