### ISSUE TITLE
creating branches best practice

### ISSUE THREAD

**Issue by rgredvig** [githubteacher/githubfordevelopers-april#33]
We just learned how to create a branch at github and then pull to local repo.

Is it good practice or not to create a branch in your local repo and then push it to github instead?

**Comment by brianamarie** [comment]
@rgredvig There is no recommended practice here. As long as branches are being created for short term purposes, it doesn't matter if you create it on the remote or locally. I'm going to close this issue, but please reopen or open a new issue if you have more questions. 😄
