### ISSUE TITLE
creating the .md file

### ISSUE THREAD

**Issue by githubstudent2016** [githubteacher/githubfordevelopers-april#35]
Can you please send me instructions to create the .md file and next steps? i missed that part - 
i had issues checking out earlier. but i am in my checked out branch now and want to add the file to my branch

**Comment by brianamarie** [comment]
- `touch githubstudent2016-hometown.md`
-  `git add githubstudent2016-hometown.md`
- `git commit -m "INSERT YOUR COMMIT MESSAGE HERE"` 

👍 

Does this help?

**Comment by githubstudent2016** [comment]
git commit is returning the following:

 git commit -m "my first commit"
On branch Githubstudent2016_Shrewsbury
Your branch is up-to-date with 'origin/Githubstudent2016_Shrewsbury'.
Untracked files:
        githubstudent2016-Shrewsbury.md

nothing added to commit but untracked files present

**Comment by brianamarie** [comment]
Ah, @githubstudent2016, it looks like you may have missed a step. Try typing `git add githubtudent2016-Shrewsbury.md`, then `git commit -m "my first commit"` again.

**Comment by githubstudent2016** [comment]
:+1:  this time it worked! Thanks!
