### ISSUE TITLE
Got error on git push?

### ISSUE THREAD

**Issue by kumardss** [githubteacher/githubfordevelopers-april#37]
fatal: The current branch kumardss-hyderabad has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin kumardss-hyderabad

**Comment by brianamarie** [comment]
> git push --set-upstream origin kumardss-hyderabad

@kumardss Did this work?

**Comment by brianamarie** [comment]
It's been about an hour, so I'm going to close this issue. Please reopen or open a new issue if you have more questions. 😄
