### ISSUE TITLE
Invalid gitfile format on push command??

### ISSUE THREAD

**Issue by welchn** [githubteacher/githubfordevelopers-april#38]
I got this issue when I tried to do a push.  The welch-charlton.md file is empty, did I need to put something in it?

C:\Users\welchn\Documents\classrepo\githubfordevelopers-april>git push welchn-charlton.md
fatal: Invalid gitfile format: welchn-charlton.md
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brianamarie** [comment]
@welchn It looks like you typed `git push welchn-charlton.md`, but all you need to type is `git push`. 

This is a distinct difference between Git and other version control systems - you aren't 'checking in' a file, you're actually pushing up your entire workspace as it appeared at that time, so you don't have to specify one file when you push. Does this help?

**Comment by welchn** [comment]
Yes, thanks!
