### ISSUE TITLE
error on git push

### ISSUE THREAD

**Issue by karajl** [githubteacher/githubfordevelopers-april#39]
I get this when trying to run git push

c4dev@sles12-karajl-dev:~/classrepo/githubfordevelopers-april> git push
fatal: '/// ATTENTION ///   Are you sure you want to push to public github.com? To override this warning run: 'git emc enable-public-push github.com/githubteacher/githubfordevelopers-april.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by brianamarie** [comment]
@karajl Try this: `git emc enable-public-push github.com/githubteacher/march-developers.git`

**Comment by karajl** [comment]
this worked for me - git emc enable-public-push github.com/githubteacher/githubfordevelopers-april.git
