### ISSUE TITLE
What is your current time span spent on GitHub/Git?

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/githubfordevelopers-april#4]
- Brand new!
- Less than 3 months?
- 3 - 6 months
- Greater than 6 months

**Comment by Xukinorris** [comment]
Less than 3 months...

**Comment by xdc7** [comment]
Greater than 6 months

**Comment by rsoeldner** [comment]
Less than 3 months

**Comment by emcjoe** [comment]
3-6

**Comment by welchn** [comment]
Brand new.

**Comment by smchone** [comment]
Brand new!

**Comment by shidhupatil1149** [comment]
3

**Comment by francm2** [comment]
Less than 3 months

**Comment by ghost** [comment]
Greater than 6 months

**Comment by ulisessol7** [comment]
Less than three months

**Comment by jrbird50** [comment]
Less than 3 months

**Comment by ckimaru** [comment]
brand new

**Comment by labajt** [comment]
Brand new

**Comment by Feterovsky** [comment]
3 - 6 months

**Comment by leef6** [comment]
Brand new!

**Comment by gallelloit** [comment]
< 6m

**Comment by jml9904** [comment]
3 - 6 months.

**Comment by shanmuga-dell** [comment]
Brand new

**Comment by ShaliniKamatam** [comment]
Greater than 6 months

**Comment by emyers123** [comment]
Less than 3 months.

**Comment by DavidGPeterson** [comment]
Brand new.

**Comment by czubocha** [comment]
3 - 6 months

**Comment by luizgglopes** [comment]
Less than 3 months

**Comment by mrgcode** [comment]
less than 3 months

**Comment by mbendure** [comment]
Brand new.

**Comment by karamheen** [comment]
Greater than 6 months

**Comment by rchillard-gov** [comment]
3-6 months! :)

**Comment by lmillea** [comment]
3 - 6 months

**Comment by thotchen** [comment]
less than 3 months

**Comment by mtrue01** [comment]
3-6 months

**Comment by RexHamilton** [comment]
3-6 months

**Comment by jongrim** [comment]
3 - 6 months

**Comment by leefp** [comment]
~3 months

**Comment by cppIr0nman** [comment]
Brand new.

**Comment by cr-tadd** [comment]
Nearly brand new to GitHub, over 8 years on git.

**Comment by ballab1** [comment]
6+ months

**Comment by kraghuram** [comment]
3-6 months

**Comment by visw2290** [comment]
Less than 3 months

**Comment by Feterovsky** [comment]
3-6 months

**Comment by gallelloit** [comment]
3-6months

**Comment by githubteacher** [comment]
:tada: @Xukinorris, @xdc7, @rsoeldner, @emcjoe, @welchn, @smchone, @shidhupatil1149, @francm2, @bungojungo, @ulisessol7, @jrbird50, @ckimaru, @labajt, @Feterovsky, @leef6, @pgbonino, @jml9904, @shanmuga-dell, @ShaliniKamatam, @emyers123, @DavidGPeterson, @czubocha, @luizguilhermegl, @mrgcode, @mbendure, @karamheen, @rchillar, @lmillea, @thotchen, @mtrue01, @RexHamilton, @jongrim, @leefp, @cppIr0nman, @cr-tadd, @ballab1, and @kraghuram are now  repository collaborators. :balloon:

**Comment by zettabytecode** [comment]
Greater than 6 months

**Comment by YamilG** [comment]
Greater than 6 months

**Comment by githubteacher** [comment]
:tada: @visw2290, @zettabytecode, and @YamilG are now  repository collaborators. :balloon:

**Comment by sxk6935** [comment]
Less than 3 months

**Comment by ichandra12** [comment]
Less than 6 months

**Comment by khaland** [comment]
Less than 3 months

**Comment by tsscam** [comment]
Hello! Less than 6 months

**Comment by karajl** [comment]
Brand new

**Comment by githubteacher** [comment]
:tada: @sxk6935, @ichandra12, @khaland, @tsscam, and @karajl are now  repository collaborators. :balloon:

**Comment by amitak** [comment]
Brand new.

**Comment by ishusinghal** [comment]
Brand New

**Comment by githubteacher** [comment]
:tada: @amitak and @ishusinghal are now  repository collaborators. :balloon:

**Comment by michaelshishkin** [comment]
Greater than 6 months

**Comment by githubteacher** [comment]
:tada: @michaelshishkin is now a repository collaborator. :balloon:

**Comment by HoangNguyen6** [comment]
Brand new

**Comment by ghost** [comment]
Greater than 6 months!

**Comment by limeri** [comment]
Just testing to see if this works.

**Comment by paulberesuita** [comment]
over 6 months

**Comment by smanjrekar** [comment]
less than 6 months

**Comment by githubteacher** [comment]
:tada: @HoangNguyen6, @michaelprflores, @limeri, and @paulberesuita are now  repository collaborators. :balloon:

**Comment by githubstudent2016** [comment]
about 3 months

**Comment by limeri** [comment]
Less than 6 months

**Comment by nmadaan** [comment]
Brand New

**Comment by elena631905** [comment]
*Brand new**

**Comment by kumardss** [comment]
4 months

**Comment by githubteacher** [comment]
:tada: @smanjrekar, @githubstudent2016, @nmadaan, @elena631905, and @kumardss are now  repository collaborators. :balloon:

**Comment by eric-m-christian** [comment]
Brand new :-)

**Comment by githubteacher** [comment]
:tada: @eric-m-christian is now a repository collaborator. :balloon:

**Comment by syeremenko** [comment]
Greater than 6 months

**Comment by githubteacher** [comment]
:tada: @syeremenko is now a repository collaborator. :balloon:

**Comment by emilym-sba** [comment]
3-6 months

**Comment by dca1320** [comment]
3-6

**Comment by sanjiv1980** [comment]
fresher

**Comment by DSHenan** [comment]
brand new

**Comment by vishn412** [comment]
3-6

**Comment by kalags** [comment]
brand new

**Comment by davidrfrench** [comment]
1 month

**Comment by rrperkit** [comment]
New

**Comment by yinglimao** [comment]
new user

**Comment by narrly** [comment]
brand new

**Comment by stephenperry74** [comment]
new user

**Comment by githubteacher** [comment]
:tada: @emilym-sba, @dca1320, @sanjiv1980, @DSHenan, @vishn412, @kalags, @davidrfrench, @rrperkit, @yinglimao, @narrly, and @stephenperry74 are now  repository collaborators. :balloon:

**Comment by phanss** [comment]
greater than 6 mos

**Comment by aoharris** [comment]
New user

**Comment by Kkondapa** [comment]
Just started

**Comment by theorybeta** [comment]
less than 3 months

**Comment by doakd** [comment]
about 1 month

**Comment by poojadesai22** [comment]
3 to 6 months

**Comment by rujutashinde** [comment]
brand new

**Comment by rgredvig** [comment]
3 months

**Comment by githubteacher** [comment]
:tada: @phanss, @aoharris, @Kkondapa, @theorybeta, @doakd, @poojadesai22, @rujutashinde, and @rgredvig are now  repository collaborators. :balloon:

**Comment by natalia-souza** [comment]
brand new

**Comment by githubteacher** [comment]
:tada: @natalia-souza is now a repository collaborator. :balloon:

**Comment by sanjiv1980** [comment]
brand new !

**Comment by ghost** [comment]
Brand new.

**Comment by GPrathyusha** [comment]
Prathysuha

**Comment by githubteacher** [comment]
:tada: @connoj16 and @GPrathyusha are now  repository collaborators. :balloon:

**Comment by yogeshpgarud** [comment]
less than 3 month

**Comment by SanjayYashawant** [comment]
6 months

**Comment by githubteacher** [comment]
:tada: @yogeshpgarud and @SanjayYashawant are now  repository collaborators. :balloon:

**Comment by wca2000** [comment]
brand new

**Comment by githubteacher** [comment]
:tada: @wca2000 is now a repository collaborator. :balloon:

**Comment by githubteacher** [comment]
👋

**Comment by GPrathyusha** [comment]
unsubscribed

**Comment by Kkondapa** [comment]
No notifications

**Comment by czubocha** [comment]
@githubteacher

**Comment by eric-m-christian** [comment]
test

**Comment by GPrathyusha** [comment]
Testing again

**Comment by SarithaPalley** [comment]
@githubstudent

**Comment by yogeshpgarud** [comment]
@githubteacher  - good to know this

**Comment by kumardss** [comment]
@githubteacher i have already subscribed but no notifications

**Comment by jrbird50** [comment]
@jrbird50

**Comment by rrperkit** [comment]
@githubteacher  - Referring teacher

**Comment by zettabytecode** [comment]
@githubteacher

**Comment by ydong8800** [comment]
6m

**Comment by githubteacher** [comment]
:tada: @SarithaPalley and @ydong8800 are now  repository collaborators. :balloon:

**Comment by MaxG117** [comment]
brand new

**Comment by githubteacher** [comment]
:tada: @MaxG117 is now a repository collaborator. :balloon:

**Comment by vedashreevinay** [comment]
1m

**Comment by githubteacher** [comment]
:tada: @vedashreevinay is now a repository collaborator. :balloon:

**Comment by brianamarie** [comment]
Congrats on a great day 1 everybody! I'm going to close this issue now since we are about finished, and I want to keep the issues clean so I don't miss any questions. 😄
