### ISSUE TITLE
unexpected EOF ... error on git push

### ISSUE THREAD

**Issue by MaxG117** [githubteacher/githubfordevelopers-april#40]
$ git push
git: 'credential-cache' is not a git command. See 'git --help'.
git credential-'cache get: -c: line 0: unexpected EOF while looking for matching `''
git credential-'cache get: -c: line 1: syntax error: unexpected end of file
git credential-'cache get: -c: line 0: unexpected EOF while looking for matching `''
git credential-'cache get: -c: line 1: syntax error: unexpected end of file

I should note that it never asked me for my github password and there were no instructions where to input it...

**Comment by brianamarie** [comment]
@MaxG117 Hm... If you type `git config --list` do you have something named `credential-cache`?

**Comment by MaxG117** [comment]
Yes, but I don't know where it came from.
credential.helper=cache
credential.helper='cache
credential.helper='cache

**Comment by MaxG117** [comment]
Sorry, I do know where it came from. It came from some of the instructions I followed before the class started.

**Comment by brianamarie** [comment]
@MaxG117 Let's try `git config --unset credential.helper` and then push again.

**Comment by MaxG117** [comment]
the unset command isn't unsetting it.

**Comment by brianamarie** [comment]
@MaxG117 Hm.... How about `git config --global --unset credential.helper`?

**Comment by MaxG117** [comment]
is there a --force or something?

$ git config --global --unset credential.helper
warning: credential.helper has multiple values

**Comment by brianamarie** [comment]
@MaxG117 There may be, but I know for sure you can edit it manually: `git config --global --edit`

**Comment by MaxG117** [comment]
nevermind, needed to use --unset-all

**Comment by tomko80** [comment]
I still get the error "git credential-'cache get: -c: line 1: unexpected EOF while looking for matching `''" after which it prompts the login. How can I make it not expect the credential help to be defined?
