### ISSUE TITLE
i have solved git push issue by using git push origin mybranch-name?

### ISSUE THREAD

**Issue by kumardss** [githubteacher/githubfordevelopers-april#42]
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 291 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/githubteacher/githubfordevelopers-april.git
 * [new branch]      kumardss-hyderabad -> kumardss-hyderabad

**Comment by brianamarie** [comment]
👍 Great, do you have any more questions?

**Comment by brianamarie** [comment]
It's been a while, so I'm going to close this issue. Please reopen or open a new issue if you have more questions. 😄
