### ISSUE TITLE
ques

### ISSUE THREAD

**Issue by 1405115** [githubteacher/githubfordevelopers-april#43]
just now i have created a branch deepak-india
but is not showing in list git branch --all 
reason ?

**Comment by githubteacher** [comment]
Hey @1405115 ! Go ahead and type `git pull` in your command line and it should pop up.

Please let us know if you have any extra questions!

**Comment by 1405115** [comment]
yeah got it :)
why git checkout deepak-india from origin 
not working ??

**Comment by brianamarie** [comment]
@1405115 Are you asking why it wasn't working before, or why it isn't working now?

**Comment by 1405115** [comment]
still this command is not working 
showing error: pathspec

**Comment by brianamarie** [comment]
@1405115 What is the output if you type `git branch --all`?

**Comment by 1405115** [comment]
list of branches including my branch deepak-india

**Comment by brianamarie** [comment]
Ok, so to checkout @1405115, type `git checkout deepak-india`.

**Comment by 1405115** [comment]
switched to a new branch message..

**Comment by brianamarie** [comment]
Great! To get caught up, you'll need to:
- create a file: `touch 1405115`
- add it: `git add 1405115.md`
- commit it: `git commit -m "first commit"`
- push to the remote: `git push`:
- Open a pull request

**Comment by 1405115** [comment]
i was using command 
git checkout deepak-india from origin .
as sir directed ..

oky i am trying your commands .

**Comment by brianamarie** [comment]
Ah, I see @1405115. Let me know if you need any  more help 😄

**Comment by 1405115** [comment]
sure :)

$ git add 1405115.md
fatal: pathspec '1405115.md' did not match any files

**Comment by brianamarie** [comment]
@1405115 When you created a file, what was the name of it?

**Comment by 1405115** [comment]
how to create a file

**Comment by brianamarie** [comment]
Type `touch <FILENAME.md>`

**Comment by 1405115** [comment]
$ touch 1405115

**Comment by brianamarie** [comment]
Ok - now you should be able to type `git add 1405115`

**Comment by 1405115** [comment]
opps sorry you gave me wrong command  earlier :)

**Comment by 1405115** [comment]
1405115@CSE1405115 MINGW32 ~/desktop/classrepo/git
$ git commit -m "my first commit"
[deepak-india bf741c9] my first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1405115

1405115@CSE1405115 MINGW32 ~/desktop/classrepo/githubfordevelopers-april (deepak-india)
$ git push
fatal: TaskCanceledException encountered.
   A task was canceled.

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Microsoft.Alm.Git.Trace.Microsoft.Alm.Git.ITrace.Flush()
   at Microsoft.Alm.Cli.Program.Die(String message)
   at Microsoft.Alm.Cli.Program.Main(String[] args)
Username for 'https://github.com':

**Comment by brianamarie** [comment]
@1405115 I think this error has to do with a configuration setting for your credential manager. Can you please type `git config --global --list` and post the output here?

**Comment by 1405115** [comment]
oky

**Comment by 1405115** [comment]
1405115@CSE1405115 MINGW32 ~/desktop/classrepo/githubfordevelopers-april (deepak-india)
$ git config --global --list
core.autocrlf=true
user.name=DEEPAK KUMAR
user.email=1405115@kiit.ac.in

**Comment by brianamarie** [comment]
Okay, thank you @1405115. Is there anything different with `git config --list`?

**Comment by 1405115** [comment]
you wlcm

**Comment by 1405115** [comment]
yes number of lines in output increases but previous output is also included in it as it is .

**Comment by brianamarie** [comment]
Okay. Can you please paste the output @1405115?

**Comment by 1405115** [comment]
1405115@CSE1405115 MINGW32 ~/desktop/classrepo/git                                                                        hubfordevelopers-april (deepak-india)
$ git config --global --list
core.autocrlf=true
user.name=DEEPAK KUMAR
user.email=1405115@kiit.ac.in

1405115@CSE1405115 MINGW32 ~/desktop/classrepo/git                                                                        hubfordevelopers-april (deepak-india)
$ git config --list
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/                                                                        ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
credential.helper=manager
core.autocrlf=true
user.name=DEEPAK KUMAR
user.email=1405115@kiit.ac.in
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/githubteacher                                                                        /githubfordevelopers-april.git
remote.origin.fetch=+refs/heads/*:refs/remotes/ori                                                                        gin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
push.default=simple
branch.deepak-india.remote=origin
branch.deepak-india.merge=refs/heads/deepak-india

1405115@CSE1405115 MINGW32 ~/desktop/classrepo/git                                                                        hubfordevelopers-april (deepak-india)
$

**Comment by brianamarie** [comment]
@1405115 Please try running `git config --unset-all credential.helper`

**Comment by brianamarie** [comment]
Then, try to push again

**Comment by 1405115** [comment]
1405115@CSE1405115 MINGW32 ~/desktop/classrepo/githubfordevelopers-april (deepak-india)
$ git push
fatal: TaskCanceledException encountered.
   A task was canceled.

Unhandled Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at Microsoft.Alm.Git.Trace.Microsoft.Alm.Git.ITrace.Flush()
   at Microsoft.Alm.Cli.Program.Die(String message)
   at Microsoft.Alm.Cli.Program.Main(String[] args)
Username for 'https://github.com': 1405115@kiit.ac.in
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 283 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 1 (delta 0)
To https://github.com/githubteacher/githubfordevelopers-april.git
   062d7e0..bf741c9  deepak-india -> deepak-india

1405115@CSE1405115 MINGW32 ~/desktop/classrepo/githubfordevelopers-april (deepak-india)
$

**Comment by 1405115** [comment]
is it on the track ??
why so many negative words in output like exceptions ,cancel ??

**Comment by brianamarie** [comment]
@1405115 I see your changes on the remote now, so I think it worked! Are you able to open a pull request? 



> why so many negative words in output like exceptions ,cancel ??

That's a good question - It likely has to do with some settings you have on your computer, maybe installed from previous work with git.

**Comment by 1405115** [comment]
oohhh oky

**Comment by 1405115** [comment]
46 pull requests . what is this pull request . i can see the list of pull request.

**Comment by 1405115** [comment]
kindly say my thanks to sir .

**Comment by 1405115** [comment]
and lots of thanks to you also.
i learned a lot .

**Comment by brianamarie** [comment]
Okay, great! Let me know if you want any more help. The review videos here will be helpful if you'd like more info before tomorrow: #128
