### ISSUE TITLE
Fatal: not a git repository

### ISSUE THREAD

**Issue by tsscam** [githubteacher/githubfordevelopers-april#47]
tssca ~ $ cd desktop
tssca desktop $ git status
fatal: Not a git repository (or any of the parent directories): .git
tssca desktop $ git log
fatal: Not a git repository (or any of the parent directories): .git
tssca desktop $

**Comment by brianamarie** [comment]
@tsscam Where were you when you cloned the repository? If you aren't sure, open up finder or explorer and search for it by name.

**Comment by tsscam** [comment]
tssca desktop $ git clone https://github.com/githubteacher/githubfordevelop
ers-april.git
Cloning into 'githubfordevelopers-april'...
remote: Counting objects: 180, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 180 (delta 1), reused 0 (delta 0), pack-reused 143
Receiving objects: 100% (180/180), 30.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3/3), done.
tssca desktop $

**Comment by brianamarie** [comment]
Ok @tsscam - getting a clean start 😄 

You will need to:
- checkout to your branch: `git checkout TSSCAMARO_Detroit`
- create a file: `touch tsscam.md`
- add it: `git add tsscam.md`
- commit it: `git commit -m "first commit"`
- push to the remote: `git push`:

**Comment by tsscam** [comment]
I appreciate your help & am getting very frustrated

tssca desktop $ git checkout TSSCAMARO_Detroit
fatal: Not a git repository (or any of the parent directories): .git

**Comment by brianamarie** [comment]
@tsscam I'm sorry to hear that you're getting frustrated. I think you're still in your desktop. What happens if you type `cd githubfordevelopers-april`?

**Comment by tsscam** [comment]
tssca desktop $ cd githubfordevelopers-april
tssca (master) githubfordevelopers-april $

**Comment by brianamarie** [comment]
@tsscam 🎉 I don't want to celebrate yet, but I think we're in the right spot! Are you able to type `git status`?

**Comment by tsscam** [comment]
YES! This all went good. I was unable to PUSH, the last step - was I suppose to PUSH the Sublime Text file I created or the file on GitHub?
THANK YOU! THANK YOU! for helping me

checkout to your branch: git checkout TSSCAMARO_Detroit
create a file: touch tsscam.md
add it: git add tsscam.md
commit it: git commit -m "first commit"

**Comment by brianamarie** [comment]
> was I suppose to PUSH the Sublime Text file I created or the file on GitHub?

Hm....I'm not sure I understand. When you push, you're pushing the commits on your current branch up to the same branch on the remote. What happened when you typed `git push`?

**Comment by tsscam** [comment]
$ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 282 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 1 (delta 0)
remote: fatal error in commit_refs
To https://github.com/githubteacher/githubfordevelopers-april.git
 ! [remote rejected] TSSCAMARO_Detroit -> TSSCAMARO_Detroit (failure)
error: failed to push some refs to 'https://github.com/githubteacher/githubfordevelopers-april.git'
tssca (TSSCAMARO_Detroit) githubfordevelopers-april
 $

**Comment by brianamarie** [comment]
@tsscam This may be because there is so much class activity at one time - if you try `git pull`, does it work? If so, try `git push` again. You got this! I appreciate your patience in this! I promise it will get easier from here. 😄

**Comment by tsscam** [comment]
YOU GOT THIS! I appreciate you SOOOO MUCH! This is how I added 

tssca (TSSCAMARO_Detroit) githubfordevelopers-april $ git pull
remote: Counting objects: 79, done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 79 (delta 11), reused 70 (delta 3), pack-reused 0
Unpacking objects: 100% (79/79), done.
From https://github.com/githubteacher/githubfordevelopers-april
   1bd3678..3623669  master     -> origin/master
Already up-to-date.

ALL GOOD! I think I'm good, now. THANK YOU!

**Comment by brianamarie** [comment]
Yay! 

![](https://media.giphy.com/media/F9hQLAVhWnL56/giphy.gif)
