### ISSUE TITLE
what is the version of git.. ?

### ISSUE THREAD

**Issue by sanjiv1980** [githubteacher/githubfordevelopers-april#5]
I am holding linux system

**Comment by brianamarie** [comment]
If you type `git --version` in your terminal, you'll see your version. As long as you're above version 2.0, you'll be good for today. 😄 I'm going to close out this issue now, but please feel free to reopen or open a new issue if you have more questions.

**Comment by sanjiv1980** [comment]
you will be going through , like how to install git hub in linux ?

**Comment by brianamarie** [comment]
@sanjiv1980 We will check the git version, but git should already be installed. Generally git comes preinstalled on linux. Are you able to type `git --version` in your terminal? What is the output?

**Comment by sanjiv1980** [comment]
Thanks , it has :+1:  

git version 1.8.3.1

**Comment by brianamarie** [comment]
Great! 🎉

**Comment by kumardss** [comment]
If you have already installed git into your machine then type git --version then you will get to know which version is @sanjiv1980
