### ISSUE TITLE
ques

### ISSUE THREAD

**Issue by 1405115** [githubteacher/githubfordevelopers-april#8]
what is .md?

**Comment by brianamarie** [comment]
Great question @1405115! `.md` is a file extension that is short for 'markdown'. Markdown helps regular text look formatted, like this:

```
# h1

- one
- two
- three
```


# h1

- one
- two
- three

----
We'll practice this more later.

**Comment by 1405115** [comment]
thanks
what is star at the top ?

**Comment by brianamarie** [comment]
@1405115 It's a way to track repositories that you like, and it's a way for GitHub to keep track of how popular some repositories are.

**Comment by githubteacher** [comment]
:tada: @1405115 is now a repository collaborator. :balloon:

**Comment by 1405115** [comment]
sorry
sometimes video get freeze  :(
i am lost.

**Comment by brianamarie** [comment]
I'm sorry to hear that @1405115. If you try leaving the webinar and coming back, it may be helpful. Also, if you end up getting behind, don't worry - we have videos that we will send after to help you fill in any gaps. Right now, we haven't started any actions, just listening so far.

**Comment by 1405115** [comment]
thanks
i am not leaving now..
trying my best to understand things.
i m brand new on this plate form.

**Comment by 1405115** [comment]
@1405115 is now a repository collaborator.
what this means ?

**Comment by brianamarie** [comment]
@1405115 Now you will be able to create a branch and participate in our next activities.

**Comment by 1405115** [comment]
oky

**Comment by 1405115** [comment]
i failed to run git checkout .......

**Comment by brianamarie** [comment]
> i failed to run git checkout .......

@1405115 What do you mean? If you type `git status` what is the output?
